[env]
LOGGING_DIR = "/Users/hayde/IdeaProjects/rust-spring-knockoff/log_out/log.log"
PROJECT_BASE_DIRECTORY = "/Users/hayde/IdeaProjects/kafka-data-subscriber"
[registries]
estuary = { index = "http://localhost:1234/git/index" }


